# Étape 1 : Construction
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

# Copier le fichier .csproj et restaurer les dépendances
COPY *.csproj ./
RUN dotnet restore

# Copier tout le code source dans l'image et construire le projet
COPY . ./
RUN dotnet publish -c Release -o /app/out

# Étape 2 : Exécution
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app

# Copier les fichiers générés par l'étape de construction
COPY --from=build /app/out ./

# Exposer le port 80 pour les requêtes HTTP
EXPOSE 80

# Définir le point d'entrée pour démarrer l'application
ENTRYPOINT ["dotnet", "solutionsapp.dll"]
